# Configuracion general de la aplicacion
spring.application.name=backend

# Configuracion de la base de datos
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuracion de JPA/Hibernate
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO}
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

# JWT Configuration
jwt.secret=${JWT_SECRET}
jwt.expiration-ms=${JWT_EXPIRATION_MS}

# Configuración del servidor de correos (SMTP)
spring.mail.host=${SMTP_HOST}
spring.mail.port=${SMTP_PORT}
spring.mail.username=${SMTP_USERNAME}
spring.mail.password=${SMTP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Configuracion del puerto del servidor
server.port=${PORT}

# URL del Frontend para los enlaces de correo
app.frontend-url=${FRONTEND_URL}

# Configuraciones personalizadas de la aplicación
app.uploads-dir=${UPLOADS_DIR}
app.api-url=${API_URL}

# Configuración del tamaño máximo para la subida de archivos (Multipart)
spring.servlet.multipart.max-file-size=${MAX_FILE_SIZE}
spring.servlet.multipart.max-request-size=${MAX_REQUEST_SIZE}
